feign:
  client:
    config:
      document:
        url: ${document.url:FAKE}
        loggerLevel: basic
        connectTimeout: 5000
        readTimeout: 2000
        errorDecoder: com.gabrielfeitosa.user.decoder.DocumentErrorDecode