name: Distributed Systems - User Service

on:
  push: 
    branches: [main]
    paths:
      - user-service/**
  pull_request:
    branches: [ main ]
    paths:
      - user-service/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: user-service
        args: >
          -Dsonar.organization=gabrielfeitosa
          -Dsonar.projectKey=distributed-system:user-service
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build with Maven
      run: cd user-service && mvn -B package -DskipTests

