name: Distributed Systems - User Service

on:
  push: 
    branches: [main]
    paths:
      - user-service/**
  pull_request:
    branches: [ main ]
    paths:
      - user-service/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: cd user-service && mvn -B package -DskipTests
